/**
 * BiliProfile Analyzer — Local Mock Data (Phase 2)
 * All data in this file is strictly for UI mockup, local testing, and structural demonstration.
 * No real user accounts, no external requests, and no unauthorized inferences.
 */

import {
  AnalysisTargetSummary,
  SelfProvidedProfile,
  TopicTaxonomyItem,
  FollowEntityItem,
  AnalysisTaskMock,
  AnalysisResultMock,
  MockQAPair,
  CategoryMetric,
} from "@/types/analysis";

export const MOCK_TARGET: AnalysisTargetSummary = {
  id: "target-demo-01",
  name: "演示分析目标 (Demo YJ)",
  platform: "BILIBILI",
  platformUid: "demo_space_202688",
  category: "人物",
  totalFollowingsSampled: 99,
  totalDynamicsSampled: 18,
  createdAt: "2026-08-20 14:30:00",
  lastAnalyzedAt: "2026-08-25 10:15:00",
};

export const MOCK_TOPIC_TAXONOMY: TopicTaxonomyItem[] = [
  {
    id: "topic-tech",
    name: "技术与数码",
    code: "TECH_DIGITAL",
    color: "#4E878C",
    description: "软件工程、计算机系统、数码硬件评测与前沿科技",
  },
  {
    id: "topic-edu",
    name: "知识学习",
    code: "KNOWLEDGE_EDU",
    color: "#D4A373",
    description: "学科辅导、公开课、英语提升、方法论与学术科普",
  },
  {
    id: "topic-ent",
    name: "影视娱乐",
    code: "ENTERTAINMENT",
    color: "#9C7A97",
    description: "电影解说、动画动漫、剧集讨论与流行文化",
  },
  {
    id: "topic-life",
    name: "生活方式",
    code: "LIFESTYLE",
    color: "#86A873",
    description: "美食日常、居家收纳、旅行见闻与个人记录",
  },
  {
    id: "topic-music",
    name: "音乐艺术",
    code: "MUSIC_ART",
    color: "#C27D66",
    description: "乐器演奏、音乐制作、视觉设计与绘画美育",
  },
  {
    id: "topic-sports",
    name: "体育运动",
    code: "SPORTS",
    color: "#5B8E7D",
    description: "羽毛球、球类竞技、健身训练与户外运动",
  },
];

export const MOCK_CATEGORY_METRICS: CategoryMetric[] = [
  { topicId: "topic-edu", topicName: "知识学习", count: 32, percentage: 32.3, color: "#D4A373" },
  { topicId: "topic-tech", topicName: "技术与数码", count: 28, percentage: 28.3, color: "#4E878C" },
  { topicId: "topic-music", topicName: "音乐艺术", count: 14, percentage: 14.1, color: "#C27D66" },
  { topicId: "topic-life", topicName: "生活方式", count: 11, percentage: 11.1, color: "#86A873" },
  { topicId: "topic-sports", topicName: "体育运动", count: 8, percentage: 8.1, color: "#5B8E7D" },
  { topicId: "topic-ent", topicName: "影视娱乐", count: 6, percentage: 6.1, color: "#9C7A97" },
];

export const MOCK_FOLLOW_ENTITIES: FollowEntityItem[] = [
  {
    id: "follow-01",
    targetId: "target-demo-01",
    name: "开源系统架构小站（演示）",
    sign: "专注分布式系统与 Rust/TypeScript 工程实践分享",
    entityType: "机构媒体",
    topicId: "topic-tech",
    topicName: "技术与数码",
    mappingMethod: "RULE_BASED",
    confidence: 0.98,
    followedOrder: 1,
  },
  {
    id: "follow-02",
    targetId: "target-demo-01",
    name: "全栈开发者日志（演示）",
    sign: "记录 Web 全栈开发与 Next.js 性能调优",
    entityType: "个人博主",
    topicId: "topic-tech",
    topicName: "技术与数码",
    mappingMethod: "RULE_BASED",
    confidence: 0.95,
    followedOrder: 2,
  },
  {
    id: "follow-03",
    targetId: "target-demo-01",
    name: "高校计算机公开课搬运（演示）",
    sign: "名校操作系统、算法与计算机网络中文精讲",
    entityType: "UP主",
    topicId: "topic-edu",
    topicName: "知识学习",
    mappingMethod: "RULE_BASED",
    confidence: 0.99,
    followedOrder: 3,
  },
  {
    id: "follow-04",
    targetId: "target-demo-01",
    name: "学术论文速览社（演示）",
    sign: "每周速读 AI 与系统领域顶会前沿论文",
    entityType: "UP主",
    topicId: "topic-edu",
    topicName: "知识学习",
    mappingMethod: "RULE_BASED",
    confidence: 0.96,
    followedOrder: 4,
  },
  {
    id: "follow-05",
    targetId: "target-demo-01",
    name: "学术英语写作指南（演示）",
    sign: "工科研究生学术论文与答辩表达提升",
    entityType: "个人博主",
    topicId: "topic-edu",
    topicName: "知识学习",
    mappingMethod: "RULE_BASED",
    confidence: 0.92,
    followedOrder: 5,
  },
  {
    id: "follow-06",
    targetId: "target-demo-01",
    name: "古典吉他研习社（演示）",
    sign: "分享指弹吉他谱与乐理练习日常",
    entityType: "个人博主",
    topicId: "topic-music",
    topicName: "音乐艺术",
    mappingMethod: "MANUAL",
    confidence: 1.0,
    followedOrder: 6,
  },
  {
    id: "follow-07",
    targetId: "target-demo-01",
    name: "羽毛球战术与步伐拆解（演示）",
    sign: "国家二级运动员带你练步法与双打配合",
    entityType: "UP主",
    topicId: "topic-sports",
    topicName: "体育运动",
    mappingMethod: "RULE_BASED",
    confidence: 0.94,
    followedOrder: 7,
  },
  {
    id: "follow-08",
    targetId: "target-demo-01",
    name: "极简生活与书房搭建（演示）",
    sign: "工科生的无杂物工作区与效率好物",
    entityType: "个人博主",
    topicId: "topic-life",
    topicName: "生活方式",
    mappingMethod: "RULE_BASED",
    confidence: 0.88,
    followedOrder: 8,
  },
  {
    id: "follow-09",
    targetId: "target-demo-01",
    name: "硬核影视叙事拆解（演示）",
    sign: "逐帧解析经典科幻电影与视听语言",
    entityType: "UP主",
    topicId: "topic-ent",
    topicName: "影视娱乐",
    mappingMethod: "RULE_BASED",
    confidence: 0.91,
    followedOrder: 9,
  },
];

export const MOCK_SELF_PROFILE: SelfProvidedProfile = {
  id: "self-profile-01",
  targetId: "target-demo-01",
  currentGoals: {
    value: "准备计算机专业毕业设计与全栈工程能力进阶",
    allowedForAnalysis: true,
    consentScope: "PERSISTENT_ACROSS_TASKS",
  },
  learningDirections: {
    value: ["现代 Web 架构 (Next.js / TypeScript)", "分布式系统基础", "学术论文写作"],
    allowedForAnalysis: true,
    consentScope: "PERSISTENT_ACROSS_TASKS",
  },
  careerOrMajor: {
    value: "计算机科学与技术专业 本科生",
    allowedForAnalysis: true,
    consentScope: "PERSISTENT_ACROSS_TASKS",
  },
  interestTags: {
    value: ["开源软件", "羽毛球双打", "指弹吉他", "效率工具"],
    allowedForAnalysis: true,
    consentScope: "PERSISTENT_ACROSS_TASKS",
  },
  questionsForAnalysis: {
    value: ["我的关注结构中技术与泛学习的比例是否平衡？", "近期是否有涉猎新领域的趋势？"],
    allowedForAnalysis: true,
    consentScope: "THIS_TASK_ONLY",
  },
  additionalContext: {
    value: "主要在晚间和周末浏览学习与技术视频，动态偶尔记录开发心得。",
    allowedForAnalysis: true,
    consentScope: "THIS_TASK_ONLY",
  },
  updatedAt: "2026-08-25 10:00:00",
};

export const MOCK_RECENT_TASKS: AnalysisTaskMock[] = [
  {
    id: "task-demo-101",
    targetId: "target-demo-01",
    targetName: "演示分析目标 (Demo YJ)",
    platformUid: "demo_space_202688",
    taskStatus: "COMPLETED",
    pipelineStage: "REPORT",
    outcome: "FULL",
    progress: 100,
    currentStageMessage: "分析报告已生成并固化证据快照",
    createdAt: "2026-08-25 10:14:20",
    completedAt: "2026-08-25 10:15:02",
    dataSourceRuns: [
      { id: "ds-01", taskId: "task-demo-101", sourceName: "演示基础资料", status: "SUCCEEDED", recordsCount: 1, durationMs: 180 },
      { id: "ds-02", taskId: "task-demo-101", sourceName: "演示关注样本", status: "SUCCEEDED", recordsCount: 99, durationMs: 820 },
      { id: "ds-03", taskId: "task-demo-101", sourceName: "演示动态样本", status: "SUCCEEDED", recordsCount: 18, durationMs: 460 },
    ],
  },
  {
    id: "task-demo-102",
    targetId: "target-demo-01",
    targetName: "演示分析目标 (Demo YJ)",
    platformUid: "demo_space_202688",
    taskStatus: "COMPLETED",
    pipelineStage: "REPORT",
    outcome: "PARTIAL",
    progress: 100,
    currentStageMessage: "演示降级完成（模拟关注列表私密，基于模拟动态与自述生成）",
    createdAt: "2026-08-22 16:30:10",
    completedAt: "2026-08-22 16:30:45",
    dataSourceRuns: [
      { id: "ds-04", taskId: "task-demo-102", sourceName: "演示基础资料", status: "SUCCEEDED", recordsCount: 1, durationMs: 190 },
      { id: "ds-05", taskId: "task-demo-102", sourceName: "演示关注样本", status: "SKIPPED_UNAVAILABLE", recordsCount: 0, durationMs: 50, message: "模拟关注私密，已跳过" },
      { id: "ds-06", taskId: "task-demo-102", sourceName: "演示动态样本", status: "SUCCEEDED", recordsCount: 18, durationMs: 410 },
    ],
  },
  {
    id: "task-demo-103",
    targetId: "target-demo-01",
    targetName: "演示分析目标 (Demo YJ)",
    platformUid: "demo_space_202688",
    taskStatus: "CANCELLED",
    pipelineStage: "COLLECT",
    outcome: "NONE",
    progress: 15,
    currentStageMessage: "用户在演示中取消了任务",
    createdAt: "2026-08-21 09:00:00",
    dataSourceRuns: [],
  },
];

export const MOCK_ANALYSIS_RESULT: AnalysisResultMock = {
  id: "result-demo-101",
  taskId: "task-demo-101",
  targetId: "target-demo-01",
  targetName: "演示分析目标 (Demo YJ)",
  platformUid: "demo_space_202688",
  summary:
    "【分析摘要（演示）】以下内容是根据本次模拟快照作出的有限解释，不代表对个人的确定判断。根据示例自述信息与 99 条模拟关注样本统计，该目标用户表现出以『知识学习（32.3%）』与『技术与数码（28.3%）』为核心双轮驱动的内容消费偏好，业余兴趣集中于音乐演奏与羽毛球运动。",
  generatedAt: "2026-08-25 10:15:02",
  outcome: "FULL",
  metricsSnapshot: {
    categoryMetrics: MOCK_CATEGORY_METRICS,
    totalSampleCount: 99,
    diversityEntropy: 2.14,
    peakActiveHours: "20:00 ~ 23:00 (晚间集中)",
  },
  selfProvidedSnapshot: {
    currentGoals: "准备计算机专业毕业设计与全栈工程能力进阶",
    learningDirections: ["现代 Web 架构 (Next.js / TypeScript)", "分布式系统基础", "学术论文写作"],
    careerOrMajor: "计算机科学与技术专业 本科生",
    interestTags: ["开源软件", "羽毛球双打", "指弹吉他", "效率工具"],
    questionsForAnalysis: ["我的关注结构中技术与泛学习的比例是否平衡？"],
  },
  publicDataObservations: [
    {
      title: "Top 2 核心领域聚合占比",
      description: "基于受控分类规则映射显示，『知识学习 (32.3%)』与『技术与数码 (28.3%)』两大门类在模拟样本中合计占比达 60.6%。",
      statValue: "60.6% (Top 2 领域占比)",
    },
    {
      title: "兴趣分布多样性 (信息熵)",
      description: "模拟样本覆盖 6 大受控领域，多样性信息熵为 2.14（中高多样性），反映出模拟关注样本跨越多个垂直领域。",
      statValue: "2.14 (信息熵指数)",
    },
    {
      title: "模拟时段分布特征",
      description: "基于 18 条模拟动态时间戳统计，模拟活跃行为集中在晚间 20:00 ~ 23:00。",
      statValue: "20:00 - 23:00 (峰值区间)",
    },
  ],
  aiClaims: [
    {
      id: "claim-01",
      dimension: "知识与学习诉求",
      claim: "结合示例自述毕业设计目标与 28 个模拟技术类关注样本，展示出计算机底层原理与全栈软件工程的自主学习倾向；这些模拟关注样本反映出显性学习输入偏好。",
      evidenceIds: ["ev-self-goal-1", "ev-metric-edu-01", "ev-metric-tech-1", "ev-follow-tech-01"],
      scope: "基于示例快照中的 28 个模拟技术关注样本及示例自述学习方向",
      uncertainty: "AI 解释 / 合理推测（演示）：自述方向与模拟关注数据高度吻合，但无法排除未纳入样本的其他学习途径",
    },
    {
      id: "claim-02",
      dimension: "兴趣与内容消费偏好",
      claim: "模拟关注样本显示，该用户可能对指弹吉他乐理与羽毛球技巧内容有持续兴趣；这仅反映可见的模拟关注偏好，不等同于线下实际爱好或完整生活结构。",
      evidenceIds: ["ev-metric-music-1", "ev-follow-music-01", "ev-follow-sports-01"],
      scope: "基于示例快照中的 14 条音乐类与 8 条体育类模拟关注博主样本",
      uncertainty: "AI 解释 / 合理推测（演示）：仅反映模拟关注博主的垂直领域分布，不代表线下实际参与频次",
    },
    {
      id: "claim-03",
      dimension: "模拟表达特征",
      claim: "结合示例学习目标与本次模拟样本，晚间活跃模式可能与自主学习安排有关；在有限的模拟文本样本中，主要呈现为技术问题排查与备忘笔记的表达倾向；这只是有限推测，不得延伸为个体性格定性。",
      evidenceIds: ["ev-metric-time-01", "ev-dynamic-sample-01", "ev-dynamic-sample-02"],
      scope: "基于近 18 条模拟动态标题与晚间 20:00~23:00 活跃时段统计",
      uncertainty: "AI 解释 / 合理推测（演示）：仅基于有限模拟文本样本与时间戳观察，严禁作任何心理或人格定性推断",
    },
  ],
  evidenceSnapshots: [
    {
      id: "ev-self-goal-1",
      taskId: "task-demo-101",
      sourceType: "SELF_REPORTED",
      evidenceId: "self_profile.currentGoals",
      title: "示例自述目标",
      excerptOrMetricValue: "准备计算机专业毕业设计与全栈工程能力进阶；方向：Next.js / TypeScript、分布式系统",
      contentHash: "sha256-a9f8b2c1d3...",
      createdAt: "2026-08-25 10:14:22",
    },
    {
      id: "ev-metric-edu-01",
      taskId: "task-demo-101",
      sourceType: "STATISTICAL_METRIC",
      evidenceId: "metric.topic.KNOWLEDGE_EDU",
      title: "知识学习分类统计",
      excerptOrMetricValue: "关注条目数: 32 人, 占比: 32.3%, 聚合来源: 模拟规则映射",
      contentHash: "sha256-f8e9a0b1c2...",
      createdAt: "2026-08-25 10:14:44",
    },
    {
      id: "ev-metric-tech-1",
      taskId: "task-demo-101",
      sourceType: "STATISTICAL_METRIC",
      evidenceId: "metric.topic.TECH_DIGITAL",
      title: "技术与数码分类统计",
      excerptOrMetricValue: "关注条目数: 28 人, 占比: 28.3%, 聚合来源: 模拟规则映射",
      contentHash: "sha256-b7e4f1a2c9...",
      createdAt: "2026-08-25 10:14:45",
    },
    {
      id: "ev-follow-tech-01",
      taskId: "task-demo-101",
      sourceType: "FOLLOW_RECORD",
      evidenceId: "follow.account.502",
      title: "模拟关注博主样本：开源系统架构小站",
      excerptOrMetricValue: "签名：专注分布式系统与 Rust/TypeScript 工程实践分享；分类：技术与数码",
      contentHash: "sha256-c3d9e8f7a1...",
      createdAt: "2026-08-25 10:14:25",
    },
    {
      id: "ev-metric-music-1",
      taskId: "task-demo-101",
      sourceType: "STATISTICAL_METRIC",
      evidenceId: "metric.topic.MUSIC_ART",
      title: "音乐艺术分类统计",
      excerptOrMetricValue: "关注条目数: 14 人, 占比: 14.1%",
      contentHash: "sha256-d4c3b2a1e0...",
      createdAt: "2026-08-25 10:14:46",
    },
    {
      id: "ev-follow-music-01",
      taskId: "task-demo-101",
      sourceType: "FOLLOW_RECORD",
      evidenceId: "follow.account.608",
      title: "模拟关注博主样本：古典吉他研习社",
      excerptOrMetricValue: "签名：分享指弹吉他谱与乐理练习日常；分类：音乐艺术",
      contentHash: "sha256-e5f6a7b8c9...",
      createdAt: "2026-08-25 10:14:26",
    },
    {
      id: "ev-follow-sports-01",
      taskId: "task-demo-101",
      sourceType: "FOLLOW_RECORD",
      evidenceId: "follow.account.712",
      title: "模拟关注博主样本：羽毛球战术与步伐拆解",
      excerptOrMetricValue: "签名：国家二级运动员带你练步法与双打配合；分类：体育运动",
      contentHash: "sha256-f6e5d4c3b2...",
      createdAt: "2026-08-25 10:14:27",
    },
    {
      id: "ev-metric-time-01",
      taskId: "task-demo-101",
      sourceType: "STATISTICAL_METRIC",
      evidenceId: "metric.active_hours.peak",
      title: "模拟时段统计值",
      excerptOrMetricValue: "统计样本: 18 条模拟动态, 峰值区间: 20:00 ~ 23:00 (晚间集中分布)",
      contentHash: "sha256-7a8b9c0d1e...",
      createdAt: "2026-08-25 10:14:48",
    },
    {
      id: "ev-dynamic-sample-01",
      taskId: "task-demo-101",
      sourceType: "CONTENT_SAMPLE",
      evidenceId: "dynamic.record.201",
      title: "模拟动态样本 #1",
      excerptOrMetricValue: "『记一次 Next.js 15 服务端组件缓存调试过程，排查了 2 个小时终于定位到了...』",
      contentHash: "sha256-a1b2c3d4e5...",
      createdAt: "2026-08-25 10:14:30",
    },
    {
      id: "ev-dynamic-sample-02",
      taskId: "task-demo-101",
      sourceType: "CONTENT_SAMPLE",
      evidenceId: "dynamic.record.202",
      title: "模拟动态样本 #2",
      excerptOrMetricValue: "『今天入手了一套新的羽毛球线，手感清脆很多，推荐给打高远球的朋友。』",
      contentHash: "sha256-9a8b7c6d5e...",
      createdAt: "2026-08-25 10:14:31",
    },
  ],
};

export const MOCK_QA_PAIRS: MockQAPair[] = [
  {
    id: "qa-01",
    question: "该用户的核心学习方向主要集中在哪些方面？",
    answer:
      "根据已锁定的示例快照与自述信息，该用户的学习方向主要集中在『现代 Web 全栈架构 (Next.js / TypeScript)』与『分布式系统基础』。支撑依据包括示例自述目标、知识学习分类统计 32.3% 及 28 个模拟技术博主关注记录。注：本回答仅检索当前示例证据快照，未触发外部网络请求。",
    referencedEvidenceIds: ["ev-self-goal-1", "ev-metric-edu-01", "ev-metric-tech-1", "ev-follow-tech-01"],
  },
  {
    id: "qa-02",
    question: "用户的非专业兴趣都有哪些？有依据吗？",
    answer:
      "根据受控分类统计，用户的显性业余兴趣主要为『音乐艺术 (14.1%)』与『体育运动 (8.1%)』，具体表现为指弹吉他乐理与羽毛球步法训练。数据来源于模拟关注列表中标记为对应领域的博主样本。",
    referencedEvidenceIds: ["ev-metric-music-1", "ev-follow-music-01", "ev-follow-sports-01"],
  },
  {
    id: "qa-03",
    question: "该画像报告是否有推断用户的性格或人格特征？",
    answer:
      "没有。依据本项目严格的安全与伦理边界规范，系统禁止任何形式的 MBTI、人格标签化定性（如沉稳、内向等）或敏感属性推断。报告仅客观呈现『模拟文本样本呈现的表达特征（工程笔记型记录）』，且明确标注了不确定性说明。",
    referencedEvidenceIds: ["ev-dynamic-sample-01"],
  },
];

export interface PipelineStageConfig {
  stage: import("@/types/analysis").PipelineStage;
  name: string;
  enName: string;
  description: string;
  stepNumber: number;
}

export const PIPELINE_STAGES_CONFIG: PipelineStageConfig[] = [
  {
    stage: "COLLECT",
    name: "准备演示样本",
    enName: "Collect",
    description: "加载演示基础资料与模拟数据样本 (Mock)",
    stepNumber: 1,
  },
  {
    stage: "NORMALIZE",
    name: "格式归一化",
    enName: "Normalize",
    description: "按白名单转换为领域统一数据结构 (Mock)",
    stepNumber: 2,
  },
  {
    stage: "CLEAN",
    name: "清洗与去噪",
    enName: "Clean",
    description: "过滤无效标记、官方机器人与去噪 (Mock)",
    stepNumber: 3,
  },
  {
    stage: "EXTRACT",
    name: "整理示例主题",
    enName: "Extract",
    description: "受控规则映射为 TopicAssignment 分类记录 (Mock)",
    stepNumber: 4,
  },
  {
    stage: "AGGREGATE",
    name: "频次聚合",
    enName: "Aggregate",
    description: "多维受控分类频次与时段矩阵聚合 (Mock)",
    stepNumber: 5,
  },
  {
    stage: "STATISTICAL_ANALYSIS",
    name: "确定性统计",
    enName: "Statistical Analysis",
    description: "程序严格计算分类占比、排行与多样性指数 (Mock)",
    stepNumber: 6,
  },
  {
    stage: "AI_ANALYSIS",
    name: "AI 语义解读",
    enName: "AI Analysis",
    description: "基于统计快照与自述进行分层结构化归纳 (Mock)",
    stepNumber: 7,
  },
  {
    stage: "SYNTHESIS",
    name: "证据快照固化",
    enName: "Synthesis",
    description: "提取并固化最小化 ReportEvidenceSnapshot (Mock)",
    stepNumber: 8,
  },
  {
    stage: "REPORT",
    name: "生成示例报告",
    enName: "Report",
    description: "组装生成分层结构化演示报告视图 (Mock)",
    stepNumber: 9,
  },
];

export const MOCK_INITIAL_TASK: AnalysisTaskMock = {
  id: "task-mock-init-01",
  targetId: "target-demo-01",
  targetName: "演示分析目标 (202688)",
  platformUid: "202688",
  taskStatus: "RUNNING",
  pipelineStage: "COLLECT",
  outcome: "NONE",
  progress: 11,
  currentStageMessage: "正在准备演示数据样本 (阶段 1/9: COLLECT)...",
  createdAt: "2026-08-28 10:00:00",
  dataSourceRuns: [
    {
      id: "ds-mock-01",
      taskId: "task-mock-init-01",
      sourceName: "演示基础资料",
      status: "SUCCEEDED",
      recordsCount: 1,
      durationMs: 120,
    },
  ],
};
